blockchain/My-Wallet-V3-Frontend

assets/js/controllers/settings/advanced_ctrl.js.coffee
assets/js/directives/bc-async-input.js.coffee

Improved validation for pbkdf2 and autologout

---

app/index.jade
app/partials/common.jade
assets/css/blockchain.css.scss
assets/css/modules/_layout.scss
assets/js/controllers/transaction_ctrl.js.coffee
assets/js/directives/scroll-to-top.js.coffee
tests/directives/scroll-to-top_spec.coffee

Custom directive to scroll to top of parent container, considering our new layout CSS

Scroll to top

---

app/partials/common.jade
assets/js/directives/scroll-to-top.js.coffee

This will fix open issue on angular in-view

Load more transactions

---

app/partials/first-login-modal.jade
app/partials/settings/addresses.jade
assets/js/controllers/settings/addresses_ctrl.js.coffee
tests/controllers/settings_addresses_ctrl_spec.coffee

Display either archived or imported addresses (not both)

Toggle address display

---

app/index.jade
app/partials/security-center.jade
app/templates/completed-level-tooltip.jade
app/templates/completed-level.jade
assets/css/blockchain.css.scss
assets/css/utilities/_bs_overrides.scss
assets/js/app.js.coffee
assets/js/directives/completed-level.js.coffee
locales/en-human.json
tests/directives/completed-level_spec.coffee

Add hover states on completed levels for the security center

Completed level tooltips

---

app/partials/request.jade
assets/js/controllers/request_ctrl.js.coffee
assets/js/directives/single-click-select.js.coffee
locales/en-human.json
tests/controllers/request_ctrl_spec.coffee

Fix UX when copying address, add dual live updates when entering amount

Receive refactor

---

app/index.jade
assets/css/blockchain.css.scss
server.coffee

Move noscript CSS into file, whitelist Angular chart CSS.

refactor(CSP): unsafe-inline CSS

---

app/index.jade
app/partials/reveal-xpub.jade
app/partials/settings/accounts.jade
assets/css/components/_bitcoin-addresses.scss
assets/js/app.js.coffee
assets/js/controllers/reveal_xpub_ctrl.js.coffee
assets/js/controllers/settings/accounts_ctrl.js.coffee
locales/en-human.json
tests/controllers/reveal_xpub_ctrl_spec.coffee
tests/controllers/settings_accounts_ctrl_spec.coffee

@abhisharma2 can you make it prettier? In particular the xpub overflows the modal on smaller displays.
After that it's ready for review @jtormey.

Reveal account xpub

---

app/partials/request.jade
assets/css/components/_bitcoin-addresses.scss
assets/css/modules/_send-receive.scss

Fixes the input field from overflowing past it's parent element in Firefox. Left aligned text while I was in here, too

fix(UI): receive modal input widths auto sizing issues

---

app/partials/request.jade
app/partials/send.jade
assets/css/components/_modals.scss
assets/css/modules/_send-receive.scss
assets/css/modules/_settings.scss
assets/css/utilities/_bs_overrides.scss

feat(UI): inline to rows in modals, right align labels

---

Gruntfile.coffee
app/index.jade
app/partials/home.jade
assets/css/modules/_home.scss
assets/css/modules/_layout.scss
assets/css/utilities/_borders.scss
assets/css/utilities/_colors.scss
assets/js/app.js.coffee
assets/js/controllers/home_ctrl.js
bower.json
karma.conf.js
tests/controllers/home_ctrl_spec.coffee

Tabular accounts

---

app/partials/reveal-xpub.jade
assets/js/controllers/reveal_xpub_ctrl.js.coffee
locales/en-human.json
tests/controllers/reveal_xpub_ctrl_spec.coffee

feat(Xpub): display warning to user before revealing Xpub

---

app/partials/send.jade
app/partials/settings/hd_address.jade
app/partials/settings/two-factor.jade
assets/css/angular-csp.css
assets/css/components/_modals.scss
assets/css/modules/_home.scss

Not leaving any screenshots since these are fixes back to what the UI used to be :smile:

Ui regressions

---

app/partials/login.jade
app/partials/signup.jade

fix(UI): don't wrap on login button, hide hand icon on small devices

---

app/index.jade
app/partials/login.jade
app/partials/recover-funds.jade
app/partials/signup.jade
assets/css/modules/_signin.scss
assets/js/app.js.coffee
assets/js/controllers/app_ctrl.js
assets/js/controllers/login_ctrl.js
assets/js/controllers/recoverFunds_ctrl.js.coffee
assets/js/routes.js.coffee
locales/en-human.json

You can now recover your wallet from outside the wallet with mnemonic

Wallet recoveryy

---

app/admin.jade
app/partials/alerts.jade
app/partials/home.jade
app/partials/modal-notification.jade
app/partials/reveal-xpub.jade
app/partials/second-password.jade
app/partials/security-center.jade
app/partials/send.jade
app/partials/settings/address.jade
app/partials/settings/hd_address.jade
app/partials/settings/import-address.jade
app/partials/settings/my-details.jade
app/partials/transaction.jade
app/partials/wallet-navigation.jade
app/templates/activity-feed.jade
app/templates/completed-level-tooltip.jade
app/templates/completed-level.jade
app/templates/helper-button.jade
app/templates/helper-popover.jade
app/templates/transaction-description.jade

@jtormey can you double check all these one way data binds and make sure we don't need a two way, before merging? Thanks!

refactor(performance): one-way data bind when we can

---

assets/js/controllers/settings/hdAddress.controller.js
assets/js/services/wallet.js.coffee

I also simplified the controller. Caveat: it still doesn't work correctly when you refresh the wallet.

Use current receive index for new address

---

assets/js/controllers/secondPassword.controller.js
assets/js/services/wallet.js.coffee

Give clearAlerts and optional context for clearing modal specific alerts

Clear alerts

---

app/partials/request.jade
app/partials/send.jade
assets/js/controllers/request.controller.js
assets/js/controllers/send.controller.js
assets/js/directives/transform-currency.js.coffee
tests/controllers/send_ctrl_spec.coffee
tests/directives/transform-currency_spec.coffee

Show placeholder 0 in Send / Receive (instead of actual value)

---

assets/js/core/api.service.js
assets/js/services/wallet.js.coffee
tests/mocks/my_wallet/my_blockchain_api_mock.coffee
tests/services/wallet/signup_login_2ndpw_sync_upgrade.coffee
tests/services/wallet_service_spec.coffee

Justin, this changes are needed in order to work with my-wallet last commit deleting BlockchainAPI. The tests are broken. I am sure you will fix them instantly.

new api integration

---

dependency-whitelist.json

https://github.com/angular-ui/ui-router/compare/0.2.13...0.2.15?w=1

chore(Whitelist): update angular-ui-router

---

assets/js/controllers/settings/addressImport.controller.js
tests/controllers/settings_address_import_ctrl_spec.coffee

Fixed address import from QR code

---

app/partials/settings/set-second-password.jade
app/templates/helper-button.jade
assets/js/directives/helper-button.js.coffee
locales/en-human.json

Warning looks like:
Consistent with info button:

Second Password: add warning button

---

app/partials/settings/security.jade
assets/js/controllers/settings/security.controller.js
locales/en-human.json

Advanced hidden:
Advanced shown:

Toggle advanced settings

---

README.md
assets/css/modules/_destination-input.scss
assets/css/utilities/_animations.scss

1. Looks like something with ngAnimate went haywire (maybe with the bootstrap update? not sure really why). Need to add some hard and fast display none/blocks to make it lose the shake.
2. Changed up the grey in the Send modal to match with the rest of the greys ;)
3. Updated README to include the bower step
Sorry for including this all in one branch, but minor things.

Shaky modal

---

assets/css/components/_activity-feed.scss

small CSS improvement
Improve readability on "Welcome to your Activity Feed" message text 
- make the white background gradient a bit more opaque
- add white background to the text element to achieve maximum readability

Improve readability on "Welcome to your Activity Feed" welcome text

---

app/partials/wallet-navigation.jade
assets/css/modules/_left-nav.scss
assets/js/controllers/app.controller.js
assets/js/controllers/home.controller.js
assets/js/controllers/navigation.controller.js
assets/js/controllers/request.controller.js
assets/js/controllers/send.controller.js
assets/js/controllers/settings/recovery.controller.js
assets/js/controllers/transactions.controller.js
assets/js/controllers/walletNavigation.controller.js
assets/js/directives/contextual-message.js.coffee
assets/js/services/wallet.js.coffee
locales/en-human.json
tests/controllers/account_form_ctrl_spec.coffee
tests/controllers/accounts_ctrl_spec.coffee
tests/controllers/reveal_xpub_ctrl_spec.coffee
tests/services/wallet/account_management_spec.coffee
tests/services/wallet/signup_login_2ndpw_sync_upgrade.coffee
tests/services/wallet_service_spec.coffee

Depends on blockchain/My-Wallet-V3/pull/56 (merged and released)

Move imported txs up in navigation

---

app/partials/settings/addresses.jade
app/partials/settings/preferences.jade
assets/js/controllers/settings/preferences.controller.js
assets/js/services/wallet.js.coffee
e2e-tests/settings/my_addresses_spec.js
locales/en-human.json

Pending blockchain/My-Wallet-V3#67

Notifications for HD addresses and setting

---

assets/css/components/_modals.scss

fix(modal): remove black bar from beneath modals

---

app/partials/recover-funds.jade
locales/en-human.json

feat(recovery): add warning to wallet recovery page

---

Gruntfile.coffee

Wraps our application in a closure, so as to not expose any functions to the global scope in production mode.

fix(tasks): wrap dist min file in iife

---

app/admin.jade
app/admin.js

This is dependent on the last commit (91ec8b6) to the beta module.

feat(admin): add pagination to prevent slow page load

---

app/partials/first-login-modal.jade
assets/css/components/_modals.scss

Ensuring that the rocket gif does not stretch with the width of screen on resize

Rocket gif alignment and aspect ratio

---

app/partials/security-center.jade
assets/css/modules/_security-center.scss
assets/js/controllers/securityCenter.controller.js

Clicking cancel on the 'link mobile number' form will now correctly toggle the state of the form.

Security link mobile

---

assets/css/modules/_settings.scss

Translation ui (settings page)

---

app/partials/settings/accounts.jade
app/partials/settings/imported-addresses.jade
assets/css/modules/_settings.scss

Accounts ui

---

assets/css/components/_notifications.scss
assets/js/controllers/send.controller.js
assets/js/services/alerts.service.js
tests/controllers/send_ctrl_spec.coffee

Clean up the success modal
Successful send now mimics successful receive alert message

Success notifications

---

assets/css/components/_alerts.scss

https://github.com/blockchain/My-Wallet-V3-Frontend/pull/261

Send success was not getting css applied to it

---

README.md
app/index.jade
assets/js/controllers/login.controller.js
assets/js/controllers/signup.controller.js
assets/js/services/wallet.service.js
tests/controllers/signup_controller_spec.coffee

A neat little dev feature I threw together. If the AUTO_RELOAD environment flag is set, the wallet will automatically log you in after a refresh and send you back to the last url you were at.

feat(dev): automatically login and go to last url when flag is set

---

app/partials/security-center.jade
assets/js/controllers/securityCenter.controller.js
tests/controllers/settings_security_center_ctrl_spec.coffee

Checked bc async inputs across the site and looks safe to merge

Security center inputs

---

app/partials/claim.jade
app/partials/request.jade
app/partials/settings/accounts.jade
app/partials/settings/import-address.jade
app/partials/settings/imported-addresses.jade
app/templates/address-book-entry.jade
app/templates/hd-address.jade
app/templates/imported-address.jade
app/templates/label-origin.jade
app/templates/transaction-description.jade
app/templates/watch-only-address.jade
assets/js/filters.js
tests/filters/escapeHtml.filter.spec.js

fix(security): escape html where ng-bind-html is used

---

app/partials/upgrade.jade
assets/css/modules/_upgrade.scss
locales/en-human.json

Warn user about upgrade consequences

---

app/templates/transaction-description.jade
locales/nl-human.json
locales/nl-robot.json

Depends on blockchain/My-Wallet-V3#104

Show when transaction is sent to/from watch-only address

---

app/partials/support.jade
app/partials/transactions.jade
app/partials/wallet-navigation.jade
assets/css/components/_modals.scss
assets/css/utilities/_flex.scss
assets/js/controllers/walletNavigation.controller.js
assets/js/routes.js
locales/en-human.json

This does a few things for UX, but mainly it won't navigate users away from a page their on. Especially helpful if their deep within the site somewhere and having issues. Adding a FAQ button might also help mitigate our tickets and encourage users to investigate their issues further. 
.

Contact Support opens in modal

---

Gruntfile.coffee
app/index.jade
app/partials/dynamic-fee.jade
app/partials/send.jade
app/partials/settings/preferences.jade
app/templates/helper-popover.jade
assets/js/controllers/send.controller.js
assets/js/controllers/settings/preferences.controller.js
assets/js/services/currency.service.js
assets/js/services/wallet.service.js
locales/en-human.json
server.js
tests/controllers/send_ctrl_spec.coffee
tests/mocks/my_wallet/my_wallet_payment_mock.coffee

Dynamic fee

---

assets/js/services/wallet.service.js
tests/services/wallet/signup_login_2ndpw_sync_upgrade.coffee

Depends on blockchain/My-Wallet-V3#160

feat(2FA): pass 2FA type along during login

---

assets/js/directives/contextual-message.directive.js
tests/directives/contextual-message_spec.coffee

Contextual Security Warning

---

app/partials/login.jade
assets/js/controllers/login.controller.js
locales/en-human.json

Shortcut to wallet id reminder on failed login attempt

---

app/partials/request.jade
app/templates/destination-input.jade
assets/js/controllers/request.controller.js

Show amount labels in all send and receive menus

---

app/partials/wallet-welcome.jade

chore(WalletWelcome): add legacy wallet creation link

---

app/templates/imported-address.jade

Transfer button

---

app/index.jade
assets/js/controllers/app.controller.js
assets/js/controllers/securityCenter.controller.js
assets/js/controllers/settings/accounts.controller.js
assets/js/controllers/settings/importedAddresses.controller.js
assets/js/controllers/settings/security.controller.js
assets/js/controllers/walletNavigation.controller.js
assets/js/directives/configure-second-password.directive.js
assets/js/directives/confirm-recovery-phrase.directive.js
assets/js/directives/imported-address.directive.js
locales/en-human.json
tests/controllers/app_ctrl_spec.coffee
tests/mocks/my_wallet/my_wallet_store_mock.coffee

- Removes complexity from auto logout
- Moves logic out of WalletStore
- Warning modal 10 sec before auto logout

Autologout

---

app/partials/send.jade
assets/css/components/_modals.scss
assets/css/modules/_send-receive.scss
assets/css/utilities/_animations.scss
assets/js/controllers/app.controller.js
assets/js/controllers/walletNavigation.controller.js

better height animation for send screen

fix(Send): transition to and from confirmation screen

---

app/partials/request.jade
assets/js/controllers/request.controller.js
tests/controllers/request_ctrl_spec.coffee

Fixes incorrect bitcoin url structure and does not update the receive qr code if a description is added.

Receive QR and bitcoin url

---

app/partials/send.jade
assets/js/controllers/send.controller.js
locales/en-human.json
tests/mocks/my_wallet/my_wallet_payment_mock.coffee

Depends on [My-Wallet-V3 194](https://github.com/blockchain/My-Wallet-V3/pull/194)
Preview (copy might need updating):

Error message when call to /unspent fails

---

assets/js/services/wallet.service.js

Keep Alerts array so we can perform a proper comparison of the next alert.

Email verification alert

---

app/partials/wallet-welcome.jade
locales/en-human.json

1. change 'Anonymous Wallet User' to 'Wallet User'
2. Reorder quotes
3. Remove slider interval
4. Add quotes to translations

Landing Page

---

app/partials/login.jade
locales/en-human.json

chore(Login): add login to legacy link on login page

---

app/partials/settings/verify-message.jade

Show DONE when verification signs or fails, editing any field will revert CANCEL, VERIFY

Verify Done

---

assets/js/services/wallet.service.js

Upgrade function renamed in My-Wallet-V3

---

assets/js/controllers/settings/addressImport.controller.js
assets/js/services/wallet.service.js
bower.json
tests/controllers/settings_preferences_ctrl_spec.coffee
tests/controllers/settings_security_ctrl_spec.coffee
tests/controllers/signup_controller_spec.coffee
tests/directives/block-tor_spec.coffee
tests/mocks/my_wallet/my_wallet_settings_mock.coffee
tests/services/wallet_service_spec.coffee

Use semistandard renamed my-wallet-v3 methods

---

assets/js/services/securityCenter.service.js
assets/js/services/wallet.service.js
locales/en-human.json
tests/services/wallet_service_spec.coffee

Update email verification status in-app

---

Gruntfile.coffee
app/index.jade
assets/css/utilities/_general.scss
assets/js/app.js

Need to fix modal animations too

fix(Landing): enable scrolling

---

app/partials/settings/preferences.jade
assets/js/app.js
assets/js/directives/configure-mobile-number.directive.js
assets/js/services/wallet.service.js
tests/mocks/my_wallet/my_wallet_settings_mock.coffee
tests/services/wallet_service_spec.coffee

Parse (some of) get-info result in My-Wallet-V3

---

app/partials/send.jade
assets/css/modules/_layout.scss
assets/css/modules/_send-receive.scss

Send confirmation screen

---

app/templates/activity-feed.jade

Uses .width-x-mobile class from https://github.com/blockchain/My-Wallet-V3-Frontend/pull/499

Activity feed

---

app/partials/navigation.jade
assets/js/controllers/navigation.controller.js
assets/js/core/metadata.service.js
assets/js/services/wallet.service.js
server.js
tests/controllers/navigation_ctrl_spec.coffee
tests/mocks/my_wallet/my_wallet_metadata.coffee
tests/services/wallet/2nd_pwd_spec.coffee
tests/services/wallet/signup_login_sync_upgrade.coffee

Use metadata service for What's New

---

app/templates/destination-input.jade
app/templates/label-origin.jade
assets/js/components/label-origin.component.js
assets/js/directives/destinationInput.directive.js
assets/js/directives/ui-select-open.directive.js
assets/js/services/format.service.js
tests/directives/destination-input_spec.coffee
tests/directives/ui-select-open_spec.coffee

Also now using ui-select in send to dropdown.

Address book in send

---

app/templates/watch-only-address.jade

Response to ticket 637. Fixes font change for imported address's watch only labels.

Address name active font fix

---

app/partials/top.jade
assets/css/utilities/_general.scss

Receive beacon changed, more compatible with Safari and mobile browsers.

Receive beacon fixed

---

app/templates/imported-address.jade
app/templates/watch-only-address.jade

Fixes the Issue of the float: right pencils causing height of labels to be bigger IN SAFARI.

Address Label Height Fix

---

assets/js/controllers/send.controller.js
assets/js/directives/destinationInput.directive.js

Comparing index and address rather than label is more accurate

Prevent send-to-self error false positives

---

app/partials/settings/change-email.jade
app/partials/settings/change-ip-whitelist.jade
app/partials/settings/change-logout.jade
app/partials/settings/change-pbkdf2.jade

Fixes the problem where user could hit enter to submit invalid forms in the settings panel. SAFARI ONLY

Stops invalid form submissions

---

app/partials/common.jade
app/partials/export-history.jade
assets/js/controllers/exportHistory.controller.js
assets/js/directives/downloader.directive.js
assets/js/services/wallet.service.js
locales/en-human.json
tests/controllers/export_history_ctrl_spec.coffee
tests/directives/downloader_spec.coffee
tests/services/wallet_service_spec.coffee

Uses new export-history endpoint and includes private notes.

Export History

---

assets/css/modules/_send-receive.scss

Fixed the broken input boxes on the custom receive modal.

Receive screen overlap fixed

---

app/templates/imported-address.jade
assets/js/directives/imported-address.directive.js
locales/en-human.json

feat(ImportedAddresses): spend imported address in settings

---

assets/js/controllers/transactions.controller.js

Transaction hash search

---

assets/js/services/buySell.service.js

Fixes blank tx feed with 2nd pw.

Check for external

---

assets/js/controllers/buy.controller.js
assets/js/core/buySell.service.js
assets/js/services/buySell.service.js
tests/controllers/buy_ctrl_spec.coffee
tests/mocks/my_wallet/my_wallet_buy_sell_mock.coffee
tests/services/buy_sell_service_spec.coffee

Depends on blockchain/My-Wallet-V3#256

Use My-Wallet-V3 service, add country to signup

---

assets/js/directives/bank-account.directive.js

https://github.com/blockchain/My-Wallet-V3/pull/257

fix(Bank Account): use recipient name

---

assets/js/controllers/buy.controller.js
assets/js/directives/bank-account.directive.js
assets/js/services/formatTrade.service.js
tests/controllers/buy_ctrl_spec.coffee
tests/directives/bank-account_spec.coffee
tests/services/buy_sell_service_spec.coffee

https://github.com/blockchain/My-Wallet-V3/pull/259

fix(Account Label): show correct account label for trades

---

app/partials/buy-summary.jade
app/templates/buy-steps.jade
app/templates/trade.jade
assets/js/controllers/buy.controller.js
assets/js/services/formatTrade.service.js
locales/en-human.json

https://github.com/blockchain/My-Wallet-V3/pull/261

fix(Tx Total): use sendAmount where applicable and format total amt

---

assets/js/services/wallet.service.js

Depends on blockchain/My-Wallet-V3#258 by @jtormey

feat(HD): increase gap from 10 to 15

---

app/partials/buy-sell.jade
assets/js/controllers/buySell.controller.js
assets/js/services/buySell.service.js

Depends on blockchain/My-Wallet-V3#262

fix(BuySell): tell user if metadata service is down

---

app/partials/buy-modal.jade
assets/js/controllers/buy.controller.js

Depends on blockchain/My-Wallet-V3#263
cc @plondon @jtormey

Quote has its own class

---

assets/js/directives/transaction-description.directive.js
assets/js/services/buySell.service.js

- Will show right after receiving btc
- Tagged by hash rather than receive address
Depends on https://github.com/blockchain/My-Wallet-V3/pull/264

Fix bought tag issues

---

app/partials/buy-modal.jade
app/templates/trade.jade
assets/js/controllers/buy.controller.js
assets/js/services/formatTrade.service.js

https://github.com/blockchain/My-Wallet-V3/pull/268
Using outAmount solves the issue where the user completes a trade but the amount does not show.

Out amount

---

app/partials/buy-sell.jade
app/templates/trade.jade
assets/js/controllers/buy.controller.js
assets/js/controllers/buySell.controller.js
assets/js/directives/trade.directive.js
assets/js/services/buySell.service.js
tests/controllers/buy_ctrl_spec.coffee

Will now use the main wallet currency if supported, otherwise account default currency (if it exists), otherwise will default to EUR.
Changing buy/sell currency no longer changes wallet currency.

Coinify currency logic

---

assets/js/directives/isignthis.directive.js
assets/js/services/formatTrade.service.js

Use rejected state to match coinify.

fix(Trade State): remove declined state, use rejected instead

---

app/partials/buy-sell.jade
assets/js/controllers/buy.controller.js
assets/js/controllers/buySell.controller.js
assets/js/directives/trade.directive.js
assets/js/services/buySell.service.js
tests/controllers/buy_ctrl_spec.coffee
tests/services/buy_sell_service_spec.coffee

Does what https://github.com/blockchain/My-Wallet-V3/pull/276 was trying to do, without bloating the metadata service.

Refresh trade when loaded into modal

---

assets/js/controllers/buySell.controller.js

Profile, trades, kycs, and payment methods will only be fetched once now.

Remove extra call to fetchProfile

---

assets/js/controllers/buysell/buy.controller.js
assets/js/controllers/buysell/buySell.controller.js
assets/js/services/buySell.service.js

Depends on https://github.com/blockchain/My-Wallet-V3/pull/282

Cancel polling when leaving the scope where poll was started

---

app/partials/buy-modal.jade
assets/js/controllers/buysell/buy.controller.js
assets/js/controllers/buysell/buyAcceptTerms.controller.js
assets/js/controllers/buysell/buySelectPaymentMethod.controller.js
assets/js/controllers/buysell/buySummary.controller.js
assets/js/services/buySell.service.js
tests/controllers/buy_ctrl_spec.coffee

In an effort to make buy.controller more manageable give the child controllers more responsibility.

Buy refactor

---

app/partials/top.jade
assets/css/_bootstrap-blockchain.scss
assets/css/elements/_buttons.scss
assets/js/app.js
assets/js/controllers/top.controller.js
assets/js/directives/on-click-copy.directive.js
assets/js/directives/single-click-select.directive.js

https://i.gyazo.com/13bbcdf3126ba2664d7eda673000af1e.gif

Receive: "copy next address" button

---

app/partials/signup.jade
assets/js/controllers/signup.controller.js
tests/controllers/signup_controller_spec.coffee

We'll need a new endpoint to get the users country code (based on IP).

Guess currency from country code

---

assets/js/components/kyc-status.component.js
assets/js/controllers/buysell/buySell.controller.js

We can now tell when a KYC is in review.

fix(KYC): handle kyc in review

---

app/partials/top.jade

Reverts blockchain/My-Wallet-V3-Frontend#685

Revert "Remove MyWallet text from top bar"

---

app/index.jade

Change title

---

app/landing.jade
locales/cs-human.json
locales/de-human.json
locales/en-human.json
locales/it-human.json
locales/ja-human.json
locales/ko-human.json
locales/nl-human.json
locales/pl-human.json
locales/tr-human.json
locales/uk-human.json
locales/vi-human.json

We're sending these strings to our translator, but that can be done before merging. Please make sure I didn't break the layout before hitting merge.

Missing localizations on landing page

---

assets/js/sharedDirectives/public-header.directive.js

Reverts blockchain/My-Wallet-V3-Frontend#698

Revert "Unhide search bar and language dropdown"

---

app/partials/buy-modal.jade
app/partials/buy-sell.jade
app/templates/buy-quick-start.jade
assets/css/utilities/_typography.scss
assets/js/controllers/buysell/buy.controller.js
assets/js/controllers/buysell/buySummary.controller.js
assets/js/directives/buy-quick-start.directive.js
assets/js/services/buySell.service.js
tests/directives/buy-quick-start_spec.coffee

Depends on https://github.com/blockchain/My-Wallet-V3/pull/298

Quote from BTC

---

app/templates/transaction-status.jade
app/templates/transaction-warning.jade
assets/css/modules/_transaction-list.scss
assets/js/directives/transaction-warning.directive.js
locales/en-human.json
tests/directives/transaction-warning_spec.coffee

Display warning for rbf/double spend txs

---

app/partials/account-form.jade
app/partials/home.jade
app/partials/settings/accounts.jade
app/partials/settings/addresses.jade
app/partials/settings/imported-addresses.jade
app/templates/bc-async-input.jade
app/templates/hd-address.jade
app/templates/imported-address.jade
app/templates/watch-only-address.jade
assets/css/modules/_home.scss
assets/css/modules/_left-nav.scss
assets/css/modules/_settings.scss
assets/js/controllers/home.controller.js
assets/js/controllers/settings/accounts.controller.js
assets/js/controllers/settings/addresses.controller.js
assets/js/controllers/settings/importedAddresses.controller.js
assets/js/directives/bc-async-input.directive.js
assets/js/directives/gradual-render.directive.js
assets/js/directives/imported-address.directive.js
assets/js/routes.js
locales/en-human.json
tests/controllers/home_ctrl_spec.coffee
tests/controllers/settings_accounts_ctrl_spec.coffee
tests/controllers/settings_addresses_ctrl_spec.coffee

Accounts revamp

---

app/partials/coinify-modal.jade
app/partials/coinify/summary.jade
app/templates/buy-quick-start.jade
app/templates/buy-steps.jade
locales/en-human.json

chore(Coinify): add in all translations

---

assets/js/directives/buy-quick-start.directive.js
tests/directives/buy-quick-start_spec.coffee

Fixes issues with changing currency selection in quick start

Quick start currency/quote

---

assets/js/components/kyc-status.component.js
locales/en-human.json

Based on my latest Coinify documentation.

Cover all possible kyc states

---

app/partials/wallet-navigation.jade
assets/js/controllers/coinify/coinifyCountry.controller.js
assets/js/controllers/walletNavigation.controller.js
assets/js/services/options.service.js
rootApp/Resources/wallet-options.json
server.js
tests/app.module.spec.js
tests/controllers/coinify/coinify_country_ctrl_spec.coffee
tests/services/buy_sell_service_spec.coffee
tests/services/options_service_spec.coffee

This expects /Resources/wallet-options.json to exist. An example file is provided for local development.

Get country options from server

---

Gruntfile.coffee
Makefile
app/index.jade
assets/js/core/constants.service.js
assets/js/services/wallet.service.js
bower.json
tests/mocks/my_wallet/blockchain_constants.coffee

Depends on blockchain/My-Wallet-V3#299

Add network option to build process for testnet

---

locales/de-human.json

Checked the other locales as well, German was the only one affected.

Do not translate pointer strings

---

.changelogrc
assets/js/controllers/navigation.controller.js
bower.json
tests/controllers/navigation_ctrl_spec.coffee

Depending on https://github.com/blockchain/My-Wallet-V3/pull/304

Support for new metadata service

---

app/partials/bank-check-modal.jade
app/partials/buy-sell-select-partner.jade
app/partials/buy-sell.jade
app/partials/sfox/buy.jade
app/partials/sfox/create.jade
app/partials/sfox/link.jade
app/partials/sfox/signup-steps.jade
app/partials/sfox/signup.jade
app/partials/sfox/verify.jade
assets/css/components/_forms.scss
assets/css/components/_modals.scss
assets/css/modules/_buy-sell.scss
assets/css/utilities/_spacing.scss
assets/css/utilities/_typography.scss
locales/en-human.json

I didn't touch email/phone verification for the most part.

Spacing and font size match design

---

app/partials/sfox/create.jade
assets/js/controllers/sfox/sfoxCreateAccount.controller.js
bower.json
tests/controllers/sfox/sfox_create_account_ctrl_spec.coffee

Requires a bower install, using a newer version of bcPhoneNumber.

Revised design for sfox signup flow

---

assets/js/controllers/coinify/coinify.controller.js
assets/js/controllers/coinify/coinifySummary.controller.js
tests/controllers/coinify/coinify_ctrl_spec.coffee

This fixes a bug when first creating a exchange account and trying to purchase.

Quote moved to paymentAccount

---

assets/js/controllers/settings/changeEmail.controller.js
assets/js/controllers/settings/manageSecondPassword.controller.js

Use My-Wallet-V3 function to check if user has any exchange account

---

app/partials/sfox/create.jade
assets/js/controllers/sfox/sfoxCreateAccount.controller.js
tests/controllers/sfox/sfox_create_account_ctrl_spec.coffee

* Removed options to change email / mobile in account creation summary
* Inline error shows if email is already registered, also has link to change email
* Signup process if email not verified or mobile number not saved is untouched

SFOX Accounts Changes

---

app/partials/trade-summary.jade
assets/css/components/_modals.scss
assets/css/utilities/_borders.scss
assets/js/services/formatTrade.service.js
assets/js/services/modals.service.js
locales/en-human.json
tests/controllers/sfox/sfox_checkout_ctrl.coffee

Trade Details

---

locales/en-human.json

replace alpha agreement with our TOS

---

app/partials/coinify-modal.jade
app/partials/trade-summary.jade
app/templates/buy-steps.jade
assets/css/components/_modals.scss
assets/js/services/formatTrade.service.js
locales/en-human.json

Bank transfer instructions

---

assets/js/services/wallet.service.js

Fixes issue of logging in with 2nd pw

Check if external exists before accessing

---

app/partials/navigation.jade
app/partials/subscribe-modal.jade

Hides the form, keeping it around if we figure out the spam issue, or decide to switch mail service.

Hide mailchimp subscription

---

app/partials/buy-sell.jade
app/partials/verification-needed-modal.jade
app/templates/buy-quick-start.jade
assets/js/controllers/buySell.controller.js
assets/js/directives/buy-quick-start.directive.js
assets/js/services/modals.service.js
locales/en-human.json
tests/directives/buy-quick-start_spec.coffee

User friendly experience for 7 day trade restriction

---

locales/en-human.json

tx in review copy update

---

app/templates/whats-new.jade
assets/js/app.js
assets/js/controllers/navigation.controller.js
locales/en-human.json
tests/controllers/navigation_ctrl_spec.coffee

Will only show if the user can buy.
Before merging:

Add buy to Whats New

---

app/partials/sfox/checkout.jade

Simple. Secure. Seamless message was moved to buy-sell-select-partner.

Remove repetitive simple secure seamless

---

app/landing.jade

Header alignment

---

app/partials/settings/preferences.jade
assets/js/controllers/settings/preferences.controller.js
tests/controllers/settings_preferences_ctrl_spec.coffee
tests/mocks/my_wallet/my_wallet_settings_mock.coffee

Btc unit display preferences

---

app/partials/sfox/create.jade

Make links to legal stuff blue

---

app/partials/popup-modal.jade
app/partials/sfox/buy.jade
app/partials/sfox/checkout.jade
app/partials/verification-needed-modal.jade
app/templates/buy-checkout.jade
app/templates/buy-quick-start.jade
assets/js/components/buy-checkout.component.js
assets/js/controllers/sfox/sfoxBuy.controller.js
assets/js/controllers/sfox/sfoxCheckout.controller.js
assets/js/directives/buy-quick-start.directive.js
assets/js/directives/popup.directive.js
locales/en-human.json
tests/directives/buy-quick-start_spec.coffee

Popup Modals Shared with Exchanges

---

app/index.jade
assets/js/app.js
assets/js/controllers/sfox/sfoxCheckout.controller.js
assets/js/controllers/sfox/sfoxLink.controller.js
assets/js/directives/sift-science.directive.js
assets/js/services/buySell.service.js
assets/js/services/wallet.service.js
rootApp/Resources/wallet-options.json
server.js

* allow using SFOX staging API in combination with blockchain
production backend
* allow custom SFOX API key, Plaid environment and Sift Science key

Allow SFOX API key and host override

---

app/partials/sfox/create.jade

@Sjors this fixes the issue you saw, where the field assumed you were in the US and gave you a +1.

Do not force country code to US

---

app/partials/sfox/link.jade
assets/js/controllers/sfox/sfoxLink.controller.js

Depends on https://github.com/blockchain/bitcoin-sfox-client/pull/5

Send sfox account name

---

app/partials/sfox/buy.jade
app/partials/sfox/checkout.jade
app/templates/buy-checkout.jade
assets/js/components/buy-checkout.component.js
assets/js/controllers/sfox/sfoxBuy.controller.js
assets/js/controllers/sfox/sfoxCheckout.controller.js
assets/js/controllers/sfox/sfoxSignup.controller.js
assets/js/routes.js
assets/js/services/modals.service.js
rootApp/Resources/wallet-options-debug.json
rootApp/Resources/wallet-options.json
tests/components/buy-checkout_spec.coffee
tests/controllers/sfox/sfox_checkout_ctrl.coffee
tests/controllers/sfox/sfox_signup_ctrl_spec.coffee

Safe for release because showCheckoutFraction can be set to 0% for 'real' users. Can set to 50% or something higher for QA to test.

Checkout first

---

app/partials/top.pug

Align R to top of BYOB

---

app/partials/settings/security.pug
assets/js/controllers/settings/manageSecondPassword.controller.js

@Sjors can you confirm that this is correct? Specifically, that exchange account is not dependent on second password?

Second password / Exchange account

---

app/partials/coinify/summary.pug
app/templates/buy-quick-start.pug

@prwelber let me know if this makes sense.

Sell quickfix fix

---

app/templates/whats-new.pug
assets/js/controllers/navigation.controller.js
locales/en-human.json
tests/controllers/navigation_ctrl_spec.coffee

Items older than 3 months won't show anymore.
What's New empty state:

What's New fixes

---

assets/js/components/buy-checkout.component.js

https://github.com/blockchain/bitcoin-exchange-client/pull/5

Use timeToExpiration

---

assets/css/modules/_left-nav.scss

Updated the CSS in the sidebar as discussed.

style(Sidebar): Remove white background from settings menu and add indentation

---

app/partials/buy-sell-select-partner.pug
assets/js/controllers/buySellSelectPartner.controller.js

On mobile using ui-select can be a pain.

Use native select at mobile width

---

app/partials/settings/preferences.pug
assets/css/components/_activity-feed.scss
assets/css/components/_filter-bar.scss
assets/css/modules/_home.scss
assets/css/modules/_left-nav.scss

Some minor CSS improvements for the wallet front-end.

Mobile css improvements

---

assets/js/controllers/buySellSelectPartner.controller.js
assets/js/services/buy-status.service.js

Fallback for non whitelisted users.
Requires a backend change to `invited: {}`

Unocoin Whitelist

---

app/partials/public.pug
app/partials/wallet.pug
assets/css/modules/_signin.scss
assets/js/components/testnet-warning.component.js
locales/en-human.json

(The 'X' on the right was removed)

Add warning banner if using Testnet

---

assets/js/directives/browserDetection.directive.js

Sign Up disabled on in app browsers

---

server.js

Depends on https://github.com/blockchain/bitcoin-unocoin-client/pull/21

Unocoin Prod URL

---

app/partials/unocoin/bank-transfer.pug
assets/js/controllers/unocoin/unocoinBankTransfer.controller.js

Bank Transfer Fix for IE

---

app/templates/buy-quick-start.pug
app/templates/sell-quick-start.pug
assets/js/components/sell-quick-start.component.js
assets/js/directives/buy-quick-start.directive.js
locales/en-human.json

TODO later: make trading disabled more robust, or move to exchange-checkout component

Coinify Service int fallback

---

assets/js/components/coinify/sell-summary.component.js
tests/components/sell-summary_spec.js

Reverts blockchain/My-Wallet-V3-Frontend#1219

Revert "fix(Coinify): use priority fee for sell txs"

---

assets/js/services/ethereum.service.js

Depends on https://github.com/blockchain/My-Wallet-V3/pull/426

Use last tx from metadata

---

assets/js/controllers/priceChart.controller.js

Just piggybacking off your commented out work

Cache chart

---

bower.json
tests/controllers/wallet_ctrl_spec.js
tests/mocks/my_wallet/my_wallet_mock.js

V1.23 release

---

assets/js/controllers/priceChart.controller.js

Reverts blockchain/My-Wallet-V3-Frontend#1317

Revert "Chart currency change"

---

app/partials/wallet-navigation.pug

Reverts blockchain/My-Wallet-V3-Frontend#1315

Revert "Exchange new tag fix"

---

app/landing.pug
assets/css/modules/_landing.scss

First stab at editing something in the V3 wallet. Would appreciate any feedback!

Add Login & Sign Up Buttons

---

app/partials/coinify/checkout.pug
app/templates/trade.pug
assets/css/modules/_buy-sell.scss
assets/js/controllers/coinify/coinifyCheckout.controller.js

Grid > Table
I had to add a bit of customization for a few things, but this should work for Completed and Pending trade histories.

Coinify Order History Grid

---

app/partials/modal-feature-disabled.pug
assets/js/components/block-alert.component.js
assets/js/controllers/buySellSelectPartner.controller.js
assets/js/controllers/wallet.controller.js
assets/js/services/alerts.service.js
assets/js/services/block-alert.service.js
assets/js/services/coinify.service.js
assets/js/services/languages.service.js
assets/js/services/sfox.service.js
assets/js/services/shape-shift.service.js
assets/js/services/unocoin.service.js
assets/js/sharedServices/env.service.js
locales/en-human.json
rootApp/Resources/wallet-options.json
tests/controllers/buy_sell_select_partner_ctrl_spec.js
tests/services/block-alert.service.spec.js

- Ability to disable specific features and partners from wallet-options
- Include custom (localized) message to explain why feature is disabled

Disable features

---

app/partials/request/request-bitcoin.pug
app/partials/send/send-bitcoin.pug
app/templates/block-alert.pug
assets/css/components/_block-alert.scss
assets/css/modules/_send-receive.scss
assets/js/controllers/request/requestBitcoin.controller.js
assets/js/controllers/send/sendBitcoin.controller.js

Ugly diffs because I had to indent some markup.

Alerts Changes

---

locales/en-human.json

Switched "programtically" to "programmatically". Seems more like what it is intended to mean.

Fixes typo in API_ACCESS_SUPPORT key, Frontend settings

---

app/templates/faq-question.pug
assets/js/controllers/faq.controller.js
rootApp/Resources/wallet-options.json

This will add a translated faqMessage to the first position in the `questions` array for the faq section.

wallet-options faq

---

app/partials/coinify-modal.pug
app/partials/coinify/summary.pug
app/templates/trade.pug
assets/js/controllers/coinify/coinify.controller.js
assets/js/controllers/coinify/coinifyMedium.controller.js
assets/js/controllers/coinify/coinifySummary.controller.js
locales/en-human.json
tests/controllers/coinify/coinify_summary_ctrl_spec.js

@prwelber can you merge this when you have a second if it looks good? `trade.receiveAmount` probably broke unocoin/sfox and I want to fix after this is merged.
Depends on https://github.com/blockchain/bitcoin-coinify-client/pull/29 which depends on https://github.com/blockchain/bitcoin-exchange-client/pull/18. You don't need to merge the *-client's yet.

Coinify BTC Fee

---

app/partials/send/send-bitcoin-cash.pug
app/partials/send/send-confirm.pug
app/templates/transaction-description-bcash.pug
assets/js/controllers/request/requestBitcoinCash.controller.js
assets/js/controllers/send/sendBitcoinCash.controller.js
assets/js/directives/transaction-description-bcash.directive.js
assets/js/services/bitcoin-cash.service.js
locales/en-human.json

New bcash addresses:
1. Request Screen
2. Send Screen
3. Transaction List
Requires: https://github.com/blockchain/My-Wallet-V3/pull/490

Bcash Addresses

---

Makefile
app/templates/exchange/upload.pug
assets/js/controllers/sfox/sfoxLink.controller.js
assets/js/controllers/sfox/sfoxUpload.controller.js
assets/js/services/sfox.service.js
locales/en-human.json
package.json

v1.30-release

---

app/partials/bitcoin-cash-address-change.pug
assets/js/constants/whats-new.constant.js
assets/js/controllers/transactions/transactionsBitcoinCash.controller.js
assets/js/services/bitcoin-cash.service.js
assets/js/services/faq.service.js
assets/js/services/modals.service.js
locales/en-human.json

BCH address format change alert

---

app/templates/transaction-description-bcash.pug
app/templates/transaction-description-ethereum.pug
app/templates/transaction-description.pug
assets/js/directives/transaction-description-bcash.directive.js
assets/js/directives/transaction-description-ethereum.directive.js
locales/en-human.json

Adds messaging to tx details when tx is unconfirmed

Tx details status msg

---

assets/js/constants/whats-new.constant.js

I commented it out rather than delete it entirely since we may bring this back. Bad practice? Should I just remove the line?

fix(What's New): remove recurring buy

---

app/partials/export-history.pug
app/partials/transactions/transactions-bitcoin-cash.pug
assets/js/controllers/export-history.controller.js

BCH Export History

---

app/partials/sfox/checkout.pug

Wiring up the view to the controllers event handler.

Removable SFOX sell banner

---

assets/js/components/exchange/exchange-create.component.js

Account Create Loop Fix

---

app/partials/buy-sell-select-partner.pug

We're going to handle this different in the next release @schnogz is working on that.

v1.32-release

---

app/templates/exchange/checkout.pug

Exchange helper

---

assets/js/controllers/home.controller.js
assets/js/controllers/sfox/sfoxSellCheckout.controller.js
assets/js/services/activity.service.js
assets/js/services/unocoin.service.js
tests/services/activity_spec.js

Add BTC buy and sell trades to activity feed

---

app/partials/buy-sell-select-partner.pug
app/partials/home.pug
locales/en-human.json

Addresses various issues with incorrect copy, an indismissible banner and a mobile copy bug.

More SFOX bug fixes

---

assets/js/controllers/home.controller.js
assets/js/services/sfox.service.js

This should fix the home screen login issues reported by some users.  It is the only place that wasn't defensively checked when looking up the SFOX exchange.

Fix home page script error

---

app/partials/public.pug
assets/css/modules/_signin.scss
assets/js/controllers/login.controller.js
assets/js/controllers/signup.controller.js
assets/js/landingCtrl.js
assets/js/routes.js
assets/js/services/wallet.service.js
assets/js/sharedServices/com-migration.service.js
assets/js/sharedServices/env.service.js
rootApp/Resources/wallet-options.json
server.js
tests/controllers/buy_sell_select_partner_ctrl_spec.js
tests/controllers/signup_controller_spec.js
tests/directives/trade_spec.js

- Configurable banner for all public views
- Automatic browser redirect to .com if wallet options flag is present
- Transfer cookies from .com using iframe

Migration -> .com

---

LICENSE.md
README.md

Add license info
