app/partials/security-center.jade, app/partials/settings/my-details.jade, app/templates/bc-async-input.jade, assets/js/directives/bc-async-input.js.coffee
* add ng-required to bc-async-input
* allow blank, by default
* disableSubmit() function
* if a field can not be empty, it won't be considered an error (red line), but submit will be disabled
=> bcAsyncInput directive improvements

app/partials/transactions.jade, assets/css/utilities/_typography.scss
Double clicking the "toggle" button on a transaction item will cause some annoying highlight. If this is the right way to fix, please merge
=> Prevent selection from happening when clicking toggle tx info button

app/partials/upgrade.jade, assets/js/controllers/app_ctrl.js.coffee, assets/js/controllers/upgrade_ctrl.js.coffee, assets/js/services/wallet.js.coffee, locales/en-human.json, tests/controllers/app_ctrl_spec.coffee, tests/controllers/upgrade_ctrl_spec.coffee
If the user cancels the 2nd password entry during upgrade, they'll be shown this.
In addition, we now show a spinner during the upgrade process and dismiss the modal afterwards. @abhisharma2 can you fix the blue background on the spinner before the merge?
=> fix(upgrade): Insist on 2nd password more clearly. Show spinner.

server.coffee
Fixes the feedback form. Without this header, feedback does not make it into the issue collector.
=> Add Atlassian header to feedback form post

app/partials/settings/addresses.jade
This solves the following (unlikely) edge case:
When the user upgrades from a legacy wallet a new BIP39 mnemonic is generated and the wallet is saved again. If this save operation fails then the next time the user logs in a different BIP 39 mnemonic is generated and the user would lose access to any funds deposited on an HD address. If the user goes to settings -> addresses and clicks New Address they would be able to send funds to themselves. 
They can't easily do this because the upgrade modal can't be dismissed, but they could manually navigate to #/settings/addresses
This fix disables the New Address button after an upgrade until the sync is complete.
=> Prevent user from generating HD address after upgrade pending sync

app/partials/top.jade, assets/css/components/_button-groups.scss, assets/css/components/_filter-bar.scss, assets/css/modules/_layout.scss
We're gonna switch the design up a bit in the "top" view to include My Wallet, Be your own bank. This will ease existing users who are used to the legacy design/nav.
=> feat(design): add "be your own bank"/branding

assets/css/components/_progress-bars.scss
Set the progress bar score to a default first time 5% score via the UI
=> feat(security-center): set default score > 0 for new wallet creation

app/partials/transaction.jade
This prevents confusion, since the historical conversion rates are calculated slightly differently than then present one.
=> Don't show historical value for the first hour

assets/css/modules/_transaction-list.scss
It seems to be related to this: http://stackoverflow.com/a/28034526
This PR fixes it for Chrome, but not for IE.
cc @abhisharma2
=> Prevent overflow of 'Verify on bc.i' in Chrome

app/partials/send.jade, assets/js/controllers/send.controller.js
The destinations list is filtered as the user types. If the user copy-pastes an address that will be the only option left. That way if they hit enter, the correct address is selected (rather than falling back to the first account).
=> fix(Send): press enter does the right thing

assets/js/controllers/send.controller.js
When you enter a value that's too high in advanced send and then reset, it keeps the "insufficient" message around and the BTC and field fields still have a red line. This PR fixes that.
=> Remove error messages on reset

assets/js/controllers/settings/addressImport.controller.js, assets/js/services/wallet.js.coffee, tests/services/wallet_service_spec.coffee
Wallet.addAddressOrPrivateKey() was called twice if a BIP38 encoded key was imported. As in the past I'm using a callback to prevent that. There might be a way to replace this callback hell with promises.
=> Only ask 2nd password once when importing BIP38

assets/js/controllers/settings/accounts.controller.js
Brackets were accidentally added (or return statement missing) in the conversion from coffeescript to ES6.
=> Show default account again

assets/js/controllers/transaction.controller.js, assets/js/controllers/transactions.controller.js, assets/js/directives/transaction-description.js.coffee, tests/controllers/transaction_ctrl_spec.coffee, tests/directives/transaction_description_spec.coffee
This solves the problem where when the user sends Bitcoin to multiple accounts, it only displays one account and the transaction total only represents one account.
* all to accounts are shown in the transaction details page
* all to accounts are shown in the transaction list page
* the transaction shows up in the from account tx list, as well as all to account tx list pages
This change depends on blockchain/My-Wallet-V3#43
=> Support displaying transactions with multiple to accounts

assets/js/controllers/settings/addressImport.controller.js
Return statement went missing during Coffee to ES6 conversion.
=> QR scan didn't work when importing address

assets/js/controllers/settings/walletSettings.controller.js, assets/js/services/wallet.js.coffee, locales/en-human.json
Because window.navigator.isProtocolHandlerRegistered() is not
implemented in any browser we can’t tell if the user already registered
bitcoin:// URI’s with our site. Clarifying that if it has already been
registered, then clicking on the button is going to have no effect.
=> Clarify handle bitcoin links UX

app/partials/settings/preferences.jade
Less wide dropdowns on desktop
Without breaking mobile:
Todo:
* email + verification doesn't look great (separate PR)
=> Settings glitches

app/templates/destination-input.jade, assets/js/directives/destinationInput.directive.js
The reason for the first blur was because clearModel gets called on load, this calls focusInput, but then the input loses focus for whatever reason, causing the blur. To fix I just decoupled focusInput from clearModel, and refer to them separately in the html
=> refactor(send): clean destination-input link code

app/partials/send.jade, app/templates/destination-input.jade, assets/css/modules/_destination-input.scss, assets/js/controllers/send.controller.js, tests/controllers/send_ctrl_spec.coffee
When there is only one account:
* Keep the from field, this makes error messaging look nicer
* Hide the accounts dropdown menu (so user cannot try to send to self)
=> feat(send): keep from field and hide account dropdown with single account

assets/js/controllers/send.controller.js
The issue was that the empty string (`''`) we use for the "All Transactions" state param is treated as a number, despite being converted to `NaN` by `parseInt()`. Because Javascript likes to keep you on your toes like that...
=> fix(Send): show default account when oppening modal from 'All Transactions'

assets/js/services/bcTranslationLoader.service.js
Load "en" by default (when there is no translation file found). Browsers use "zh_CN" for Chinese Simplified, which is now reflected in the translation file map.
=> Prevent translation load failing with unknown language code

app/partials/security-center.jade, assets/css/modules/_security-center.scss
UI issue regarding notifications overlapping in the security center when languages are changed. Removed hard coded heights, heights are now dynamic depending on the length of text.
=> Security translations ui

app/partials/security-center.jade, app/templates/completed-level.jade, assets/css/utilities/_animations.scss
New chrome was messing up the aspect ratio of the images when it was set to flex column
=> Security center image (icon) ratio

assets/js/controllers/signup.controller.js, assets/js/services/bcTranslationLoader.service.js
It was not possible to switch to Chinese if the browser language was not Chinese. I believe I fixed it now so that:
1 - when the browser language is Chinese, the registration form guesses Chinese as the language and sets the correct setting
2 - if the browser language is English, the user can switch to Chinese
I only tried this with simplified chinese, not with traditional chinese.
=> Support Chinese both as browser language and as setting

app/partials/settings/change-password.jade, app/partials/settings/preferences.jade, app/templates/activity-feed.jade, app/templates/bc-async-input.jade, assets/js/controllers/send.controller.js, assets/js/controllers/settings/changePassword.controller.js, assets/js/directives/bc-async-input.directive.js, locales/en-human.json
Several medium-priority issues fixed:
* User can no longer set main password to their email address
* If sending fails, allow pressing "send" again to retry (especially useful if send failed due to inability to set public note)
* Currency values in activity feed now get converted to whatever the display currency is, rather than only btc
* Allow addition of a "unit" to bc-async-input directives, so that settings can have a unit (for example: logout time, which now has a "minutes" unit)
=> Medium priority

assets/js/controllers/send.controller.js
Before, the internal promise of the payment object would end when buildbeta failed. Returning the payment object from the catch callback allows continuing the payment process.
=> fix(send): pass payment through error

app/index.jade, assets/js/controllers/request.controller.js, assets/js/controllers/send.controller.js, assets/js/services/format.service.js, bower.json, dependency-whitelist.json, tests/services/currency.service.spec.js, tests/services/format.service.spec.js
Don't forget to `bower update`. 
We were using a custom fork of ui-select pending a PR I made with them a while ago. This has been merged and a new version has been released, so using that. 
Unfortunately the receive modal started to freeze up. I reused the format origin code from the send screen, put it into a separate service and added some tests.
I don't know why one currency service test suddenly started breaking.
=> Format service and ui-select upgrade

Gruntfile.coffee, README.md, app/index.jade, assets/js/controllers/send.controller.js, assets/js/core/rng.service.js, assets/js/services/wallet.service.js, server.js, tests/mocks/my_wallet/my_blockchain_rng_mock.coffee
It defaults to `api.blockchain.info` is used by the dynamic fees endpoint as well as the RNG endpoint.
The deploy script remains the same, but the last argument now refers to the API rather than the dynamic fees endpoint.
=> Allow custom API domain for fees and RNG

app/index.jade, app/partials/send.jade, app/partials/settings/import-address.jade, app/templates/destination-input.jade, app/templates/qr-scan-button.jade, app/templates/qr-scan-popover.jade, assets/css/blockchain.css.scss, assets/css/components/_modals.scss, assets/css/components/_qr-scan.scss, assets/css/modules/_destination-input.scss, assets/css/modules/_send-receive.scss, assets/js/controllers/send.controller.js, assets/js/controllers/settings/addressImport.controller.js, assets/js/directives/destinationInput.directive.js, assets/js/directives/qr-scan.directive.js, locales/en-human.json, tests/controllers/send_ctrl_spec.coffee, tests/directives/destination-input_spec.coffee, tests/directives/qr-scan_spec.coffee
@plondon we talked about adding something like this a few weeks ago, so I took a few minutes to put this together. All the functionality is there, but it might need some design help (in advanced send in particular).
=> Move QR scanner to popover window

assets/js/controllers/send.controller.js, locales/en-human.json
Takes advantage of - but does not require - blockchain/My-Wallet-V3#169
@plondon @larskrueger you can now customize messages such as "No coins to spend"
cc @pernas
=> Send: translatable error messages

app/partials/transactions.jade, app/templates/transaction-description.jade, assets/js/controllers/transactions.controller.js, assets/js/directives/transaction-description.directive.js, tests/directives/transaction_description_spec.coffee
Gets rid of any noticeable lag when navigating between / in transaction lists by:
* Adding one-way binding to expressions that don't need reevaluation to reduce watcher count
* Gradually rendering transactions on scroll
* Creating a filteredTransactions alias to prevent unnecessary list traversals
=> Transaction List Performance

tests/controllers/account_form_ctrl_spec.coffee, tests/controllers/request_ctrl_spec.coffee, tests/controllers/settings_address_import_ctrl_spec.coffee, tests/controllers/settings_change_password_ctrl_spec.coffee, tests/controllers/signup_controller_spec.coffee
Now these controllers will use the actual jade templates, rather than the handwritten html strings. This lets us catch errors in the markup and makes tests more maintainable.
=> Compile controller tests from template cache

app/index.jade, app/templates/password-entropy.jade, assets/js/app.js, assets/js/directives/min-entropy.directive.js, assets/js/directives/password-entropy.directive.js, bower.json, karma.conf.js, tests/controllers/settings_change_password_ctrl_spec.coffee, tests/directives/password-entropy_spec.coffee, tests/mocks/my_wallet/my_wallet_helpers.coffee
Adapted from repo owned by @pernas: https://github.com/pernas/angular-password-entropy
Easier to maintain if it's in the frontend codebase.
=> Move angular-password-entropy dependency into frontend

assets/js/controllers/login.controller.js, assets/js/controllers/lostGuid.controller.js, assets/js/controllers/navigation.controller.js, assets/js/controllers/recoverFunds.controller.js, assets/js/controllers/resetTwoFactor.controller.js, assets/js/controllers/signup.controller.js, assets/js/services/wallet.service.js, bower.json, package.json, server.js, tests/controllers/login_ctrl_spec.coffee, tests/controllers/lost_guid_ctrl_spec.coffee, tests/controllers/reset_two_factor_ctrl_spec.coffee, tests/services/wallet/signup_login_2ndpw_sync_upgrade.coffee, tests/services/wallet_service_spec.coffee
`MyWallet.login()` is now a promise and takes a lot fewer parameters.
=> WalletService: use reorganized login() parameters

app/index.jade, assets/js/controllers/wallet.controller.js, tests/controllers/wallet_ctrl_spec.coffee
Cancels the logout interval when scope is destroyed, fixes some weird behavior that I noticed with auto logout.
=> Prevent multiple logout timers from running at once

app/partials/settings/change-password.jade, app/templates/completed-level-tooltip.jade, app/templates/completed-level.jade, assets/js/controllers/settings/changePassword.controller.js, assets/js/directives/completed-level.directive.js, assets/js/services/alerts.service.js
In the latest version of angular-translate, `$translate()` will only resolve if it can find a matching translation string, otherwise it will reject. This is a change from the previous version we were on, which would resolve with the argument (even if it wasn't a translation string). This caused alerts to not display in cases where we don't have translation strings in place.
This commit makes it so the alert will display even if no translation string is found.
=> Translate alert message in template

Gruntfile.coffee, Makefile
This is useful for backend development.
Made sure Grunt handles `:` correctly and replaces https with http and `wss` with `ws` when building for `localhost` deployment.
=> Allow localhost:8080 build

app/partials/settings/security.jade, app/templates/confirm-recovery-phrase.jade, assets/js/controllers/settings/security.controller.js, assets/js/directives/confirm-recovery-phrase.directive.js, tests/controllers/settings_security_ctrl_spec.coffee, tests/directives/confirm-recovery-phrase_spec.coffee
Reverted f1e1bde185e5d39e967bd788c4dbbf9841a20267 to bring back confirm-recovery-phrase directive.
=> Show confirm recovery phrase button in security center

app/templates/transaction-note.jade, assets/css/modules/_transaction-list.scss
In tx feed, one can no-longer have a single, long word which covers other elements
=> tx-notes no longer able to have one long word overlapping

app/partials/recover-funds.jade, assets/css/modules/_signin.scss
clicking off of empty input would shift the relative elements down enough that the button wasn't within the original click range. increasing the button's height allows user to click off the default input box and still trigger the back button.
=> fix(Recover Funds, step 2): form invalidation no longer stops button

app/partials/trade-summary.jade
Although this will never actually be an issue IRL because bank transfers take a day or more and I doubt people will leave this modal open for that long, it will help QA. Need to remove the bindings so that the actual tx values update when the trade goes from pending user action to pending coinify action.
=> fix(Bank Transfer): remove binding to prop and val so trade can update

app/templates/buy-quick-start.jade, assets/js/directives/buy-quick-start.directive.js
transaction.fiat was slow to update in the html, so pressing enter right after entering an amount would cause the modal to open with the old amount. Putting the logic into the scope makes it more responsive.
=> Prevent quickstart input and buy modal amounts from disagreeing

assets/js/routes.js
Angular UI Router would silently throw an error and freeze up, since it wasn't able to resolve Wallet.
=> Prevent blank page when refreshing on settings/:account/addresses

assets/js/services/buySell.service.js, tests/controllers/coinify/coinify_ctrl_spec.coffee
Caused from removing https://github.com/blockchain/My-Wallet-V3-Frontend/pull/760/commits/c6ce8763bca64add46cb266b37b0d2c56bbc7af3#diff-5f679bb1044ec5b38b4c2cc12d1cb894L9 because I didn't see `pending` as a possible trade state for trades, but didn't check KYCs
=> Bank transfer should trigger KYC

assets/js/directives/buy-alert.directive.js, assets/js/directives/contextual-message.directive.js, tests/directives/buy-alert_spec.coffee, tests/directives/contextual-message_spec.coffee
The two directives did not have isolated scopes, so they were essentially sharing the variables that determined when they were open.
=> Isolate scopes to prevent opening contextual message simultaneously

app/partials/wallet-navigation.jade, assets/js/controllers/buySell.controller.js, assets/js/controllers/wallet.controller.js
For users with an account, but who's email address is not whitelisted (e.g. because they changed it) the production wallet currently has a bug. It will show the tab, but clicking on it won't work, because the routes file still uses the old rules.
This would also allow users in other countries to manually navigate to the buy tab, provided their email is whitelisted.
This fix still has duplicate code, so may need some refactoring.
=> Buy page should use same rules as tab for when to show

assets/js/controllers/buySell.controller.js, assets/js/controllers/buySellSelectPartner.controller.js, assets/js/services/buyStatus.service.js, rootApp/Resources/wallet-options-debug.json, rootApp/Resources/wallet-options.json, tests/controllers/buy_sell_select_partner_ctrl_spec.coffee
Please double check my logic here...
* get sfoxWhitelist from config file
* always show buy-sell tab for Coinify countries
* move redirect to buySellSelectPartner controller
* buyStatus.canBuy() also returns true if user has an account
=> New buy-sell tab rules

assets/js/controllers/sfox/sfoxCheckout.controller.js, assets/js/services/sfox.service.js, assets/js/services/wallet.service.js, tests/controllers/sfox/sfox_checkout_ctrl.coffee, tests/services/wallet_service_spec.coffee
Won't work correctly until https://github.com/blockchain/bitcoin-sfox-client/pull/1 is merged.
* Start watching for SFOX trade txs after login
* Refresh trade before trade summary is opened to load amount
* Watch trade after checkout
Starting to see some duplication between this and Coinify, will work on minimizing that next week.
=> Show success modal when bitcoin is received

app/partials/settings/manage-second-password.jade
Fixes the issue where a user can be prevented from removing 2nd password if their password hint or main password is somehow the same (might've been set that way on legacy).
=> Remove input restrictions when removing 2nd pw

app/partials/wallet-navigation.jade, assets/js/controllers/buySellSelectPartner.controller.js, assets/js/controllers/walletNavigation.controller.js, assets/js/services/buyStatus.service.js, karma.conf.js, package.json, rootApp/Resources/wallet-options-debug.json, tests/_prepare_spec.js.coffee, tests/services/buy_status_service_spec.coffee
=> Show invite form to percentage of users

app/partials/buy-sell.jade, app/templates/buy-quick-start.jade, assets/js/controllers/buySell.controller.js, assets/js/directives/buy-quick-start.directive.js, assets/js/directives/trade.directive.js, locales/en-human.json
This can be used as a fallback to prevent !canTrade errors later in the flow.
=> Disable trading when trade is pending

app/partials/buy-sell.jade, app/templates/buy-quick-start.jade, assets/js/controllers/buySell.controller.js, assets/js/directives/buy-quick-start.directive.js
If canTrade is set properly after first purchase is initiated, use this branch.
Depends on Coinify bug fix.
=> Use canTrade flag for disabling trades

app/partials/request.jade
=> Prevent leading space from being copied with address

Gruntfile.coffee
Only calls shell:webpack when helperApp changes are made. Brings template build down from 20-22sec to 5-6sec.
=> Faster Builds

assets/js/controllers/sfox/sfoxCheckout.controller.js, assets/js/services/modals.service.js, assets/js/services/sfox.service.js, tests/controllers/sfox/sfox_checkout_ctrl.coffee
Wasn't able to use `openOnce`, which prevents more modals from opening. Instead I added `dismissPrevious`, which will close the last modal before opening a new one.
=> Only allow one trade summary modal at a time

assets/js/controllers/settings/info.controller.js, assets/js/directives/confirm-recovery-phrase.directive.js, assets/js/services/wallet.service.js, tests/controllers/settings_info_ctrl_spec.coffee, tests/directives/confirm-recovery-phrase_spec.coffee
For showing pairing code and viewing backup phrase. Removed because this feature is annoying and adds negligible security advantages.
=> Remove main password restriction

assets/js/controllers/send.controller.js
The prevents the duplicate fee issue after a failed send or after a rebuild by setting the fee to 0 after it's been used.
=> Reset fee after build step

app/partials/recover-funds.pug
Seems like Angular has no problem submitting invalid forms on Safari.
=> Prevent bypassing incorrect recovery phrase (Safari)

app/partials/request.pug, assets/js/controllers/request.controller.js, tests/controllers/request_ctrl_spec.coffee
1. Swaps btc and fiat fields
2. Uses last amount type entered for generating request
3. Reset's copy when amounts or label is changed
4. Adds tests for paymentRequestURL function
=> Use last amount type for payment request

.eslintrc.json
Directives and components already follow this filename convention, but controllers don't. I'll start renaming stuff if you're happy with the new rule.
=> Require filenames like my-little-pony.controller.js

.eslintrc.json, Gruntfile.coffee, app/index.pug, assets/js/wallet-app.module.js, assets/js/whats-new.constant.js, check_bad_strings.rb, karma.conf.js
Depends on #1092; I can redo it if we change that rule.
The first commit renames the file, removes the unneeded `use strict` and ignores the linter warning around the browser detection code (since that is non-angular code anyway).
The second commit moves the What's new constants into its own file.
I'm pretty sure this doesn't break grunt (dist), but that might need some double checking.
=> Extract constants

assets/css/modules/_security-center.scss
Fixed a small issue that caused the paragraph text to overflow the width of the container on mobile.
=> Security mobile paragraph style fix

app/partials/coinify/medium.pug
Removing these classes stacks the payment mediums on mobile width
=> Correctly stack mediums on mobile

assets/js/directives/download-button.directive.js, tests/directives/download-button_spec.js
Prepending this special character tells Excel to import the csv file as utf8, so that currency symbols don't get mangled in the resulting spreadsheet. This has been tested in Excel (on Mac), Google Sheets, and some text editors. Behaves as expected in all, although a review by someone who knows more about this than I do would be nice.
=> Export: Read utf8 properly in Excel

assets/js/components/sell-quick-start.component.js, assets/js/controllers/coinify/coinifySell.controller.js, tests/components/sell-quick-start_spec.js, tests/controllers/coinify/coinify_sell_spec.js
This will use the new fee service for sell, defaulting to the priority fee for < 1 hr confirmation time.
=> Use new priority fee for sell

assets/css/modules/_send-receive.scss, assets/js/controllers/export-history.controller.js, assets/js/controllers/transactions.controller.js, assets/js/services/wallet.service.js, locales/en-human.json
It looks like at one point 'destinations' in the transaction were outputs filtered by `!change`, but then we added another check to make sure they were not the same address as an input. https://github.com/blockchain/My-Wallet-V3-Frontend/commit/e396f6040c17bc45118e67f46a7bbb47622daf35#diff-d055a71329975bd2903700e75dd34665L16. It was a year ago, not sure if anyone knows why.
I snuck a translation fix for 'All Accounts' in here as well. Here is the important change: https://github.com/blockchain/My-Wallet-V3-Frontend/pull/1160/files#diff-ec46870014d4acb6e20b619fc6379da0R755
=> Destinations

app/templates/shapeshift/confirm.pug, assets/js/components/shapeshift/shift-create.component.js
Frontend was calling https://github.com/blockchain/My-Wallet-V3/blob/master/src/eth/eth-account.js#L129 with `getAvailableBalance(false)`, causing the incorrect max limit to be used. This passes `undefined` so `getAvailableBalance` can correctly use default gas prices.
=> Shift Eth Max

app/landing.pug, assets/css/modules/_signin.scss
This PR allows the footer to use the shared CSS footer module. Requires the branch `nav-footer-refactor` from `brand-assets`.
📦 [PR-20](https://github.com/blockchain/brand-assets/pull/20) (brand-assets)
=> refactor(Footer): Use shared footer module

assets/js/services/currency.service.js, tests/mocks/my_wallet/my_blockchain_api_mock.js, tests/services/currency.service.spec.js
This handles problems caused by dividing a num by 0 and then performing an operation on it (NaN). Only for BTC right now.
=> BTC Conversion Fix

assets/js/components/shapeshift/shift-create.component.js, tests/components/shapeshift/shift-create_spec.js
Fixes issue where minimum deposit amount messages were not displaying when users selected BCH as the outbound currency in a ShapeShift transaction.
=> Ensure all coin pairs show minimum deposit amount for ShapeShift transactions

assets/js/controllers/export-history.controller.js, assets/js/services/date-helper.service.js, tests/controllers/export-history.controller.spec.js
**Overview**:
Fixes issue where users could choose a BCH history export start date before the actual existence of BCH (August 1, 2017).  
**Changes**:
- Added BCH chain start date property to `date-helper.service.js`
- Added a `coinCode` check to `export-history.controller.js` to dynamically determine the appropriate  earliest history start date
- Wrote unit tests for both BTC and BCH scenarios
=> Dynamically determine earliest history export start date

app/partials/send/send-bitcoin-cash.pug, app/partials/send/send-bitcoin.pug, app/templates/label-origin.pug, assets/css/modules/_send-receive.scss, assets/js/components/label-origin.component.js, assets/js/controllers/send/sendBitcoin.controller.js
- Fixes an issue where users with many wallets and imported addresses were unable to quickly find wallets/addresses of value when sending funds.
- Truncates imported addresses to ensure the address holding amount is displayed in the dropdown options.
- Added hover text to addresses that will show the full addresses after 500 milliseconds.
- Removed some unnecessary CSS
=> Order wallets and then addresses by value

tests/controllers/coinify/coinify_sell_spec.js
This unit test failed pretty consistently on TravisCI due to lag.  Fix is ensure the two timestamps are within 3 milliseconds of each other instead of equal.
=> Fix timeToExpiration Coinify sell unit test

assets/js/services/activity.service.js
Fixes an issue in which BCH and ETH transaction watchers were being initialized without `MyWallet.wallet` being defined.  This resulted in infinite `$digest` calls being ran when a user refreshed their browser.
=> Smarter transaction watchers

assets/js/services/wallet.service.js
Shapeshift, BCH, and ETH promises cannot resolve when on testnet and `didFetchTransactions` never gets called. Send controller is watching `status.didLoadBalances` which gets set to `true` in `didFetchTransactions`, so that's why testnet send was displaying spinners.
=> Fix send on testnet

assets/js/directives/download-button.directive.js
For some reason this was causing the export history function to not work. It would quickly open and close a new tab instead of actually triggering a download. Weird, since this directive hasn't been touched in a long time. Maybe a browser update broke it?
=> Fix download button
